d/t/control: run suricata -u from the source tree
In the test environment, ww build a version of suricata with unittest
enabled. We should run this binary instead of the one installed by the package
which doesn't contains unittest.

In case we run `suricata -u' without tests enabled, the result is:

 ERROR: Unit tests not enabled. Make sure to pass --enable-unittests to configure when building.

Signed-off-by: Arturo Borrero Gonzalez <arturo@debian.org>